#######################################################
# Build Evironment for Meckminecraft Server 
# 
# Start with docker-compose
# 
# docker compose up -build oder -d
# (c) 2022, (c) 2025 cndrbrbr
# 05.01.2023 Update Migration meckminecraft 2023 (cndrbrbr)
# 30.11.2025 Update Migration meckminecraft 2025 (cndrbrbr)
#############################################################
version: "3.3"   
services:
  mcagjava8:
    image: mcagjava8
    build:
      context: ../../java/java8
      dockerfile: Dockerfile
  mcagjava22:
    image: mcagjava22
    build:
      context: ../../java/java22
      dockerfile: Dockerfile
  buildcmc:
    depends_on:
      - mcagjava22
    image: buildcdmc
    build:
      context: ../../minecraftbuild/buildCmc
      dockerfile: Dockerfile
    volumes: 
      - buildspimcC_data:/root/mcCsoftware    
  build8mc:
    image: build8mc
    depends_on:
      - mcagjava8
    build:
      context: ../../minecraftbuild/build8mc
      dockerfile: Dockerfile
    volumes: 
      - buildspimc8_data:/root/mc8software    
volumes:
  buildspimc8_data:
  buildspimcC_data:
