############################
#  docker compose up -d
#  docker exec -ti barejavamc-mc-1 /bin/bash
#  Just get Java and start 
#  minecraft servers manually
############################
services:
 mc:
    image: baremc22
    volumes:
      - mcsrv25:/root/data
      - /srv/sshkeys:/keys:ro
    ports:
      - "25565:25565"
      - "25566:25566"
      - "25567:25567"
      - "25568:25568"
      - "8123:8123"
volumes:
  mcsrv25:
