#######################################################
# Pullserver for Meckminecraft Server 
# docker compse build
# Start with docker-compose up -d
# console: docker exec -ti sftp_cloud /bin/bash 
#
# docker compose up -build oder -d
# (c) 2025 cndrbrbr
# 01.01.2026 use the pullserver for nc3
#############################################################
version: "3.8"

services:
  cloud:
    build: .
    container_name: sftp_cloud
    ports:
      - "2222:22"
    environment:
      SFTP_USER: "user1"
      SFTP_UID: "1000"
      SFTP_GID: "1000"
    volumes:
      - /srv/cloud:/data
      - /srv/sshkeys:/keys:ro
      # optional: persist host keys (verhindert Hostkey-Wechsel)
      - sftp_etc_ssh:/etc/ssh
    restart: unless-stopped

volumes:
  sftp_etc_ssh:


